PORT        =   2021    # port used to listen
FILENAME    =   "file.txt"
FILESIZE    =   8       # MB
MAX_BACKLOG =   10      # connections allowed hanging up
PACKETSIZE  =   1024
MAX_FILE    =   12      # Maximum files to create
FILE_OVER_FLOW  =   "OVERFLOW"
NR_HOST     =   6        # 12 is able to run all shell script offered
NR_THREAD   =   4